### PR TITLE
Firewall workbook application rule log changes

### PR DESCRIPTION
**Pull request by reijoh**
- Queries missing log entries where msg_s !has 'Web Category:' and msg_s has '. Url' and msg_s has '. No rule matched'
- rowLimit at default 250 is a bit small, increased to 10000 because I think that is more useful
- fallbackResourceIds is for a specific environment, better to use generic "Azure Monitor"
- Fix query for SourceIPAddress (Investigation tab)
    The '{SelectedSubscriptionId}' from the 'FQDN Traffic by Count' query is not the Subscription for the VM, it is the subscription for the firewall. Therefore the 'SourceIPAddress' query will not find any VM when filtering on this subscription id.
- Fix Azure Firewall Resource List query
    The ProvisionedState column show FW is not running because it query for properties.ipConfigurations.[0].properties.provisioningState property, this property is not present for Microsoft.Network/azureFirewalls running as part of Virtual Hub.

### CODE REVIEW

**Comment by anthony-roman** [comment]
@Chris ***@***.***> will you and @Tobi ***@***.***> validate these changes please?

-Anthony

From: Reidar Johansen ***@***.***>
Sent: Friday, April 9, 2021 10:44 AM
To: Azure/Azure-Network-Security ***@***.***>
Cc: Anthony Roman ***@***.***>; Review requested ***@***.***>
Subject: [Azure/Azure-Network-Security] Firewall workbook application rule log changes (#37)


  *   Queries missing log entries where msg_s !has 'Web Category:' and msg_s has '. Url' and msg_s has '. No rule matched'
  *   rowLimit at default 250 is a bit small, increased to 10000 because I think that is more useful
  *   fallbackResourceIds is for a specific environment, better to use generic "Azure Monitor"

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Azure/Azure-Network-Security/pull/37<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37&data=04%7C01%7CRoman.Anthony%40microsoft.com%7C3f865d2446154df4696208d8fb65d9a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762149873062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hbc2n1OzxjB50T032VBA4L%2Biyz3fFf7QaZiyiRmA0Mw%3D&reserved=0>

Commit Summary

  *   Firewall workbook application rule log changes
  *   Firewall workbook application rule log changes

File Changes

  *   M Azure Firewall/Workbook - Azure Firewall Monitor Workbook/Azure Firewall_ARM.json<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37%2Ffiles%23diff-e54c61dfe845ded55e2ac0808377cf7d9de7bedf3be35ab7981c414bd3f9a116&data=04%7C01%7CRoman.Anthony%40microsoft.com%7C3f865d2446154df4696208d8fb65d9a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762149873062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lfGpvOpobg%2BLxoPf%2Fwbjo9QBSaLoJZTI9S3%2FRlj5EGQ%3D&reserved=0> (36)
  *   M Azure Firewall/Workbook - Azure Firewall Monitor Workbook/Azure Firewall_Gallery.json<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37%2Ffiles%23diff-bad4158317c6e17b3a5100d1747cdfb674e1c61234ac354d1e17f26a264226c9&data=04%7C01%7CRoman.Anthony%40microsoft.com%7C3f865d2446154df4696208d8fb65d9a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762149883061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DOKl18OTrnsTY4XTppK4buevknkCAnV7kisBfLrvpuo%3D&reserved=0> (35)

Patch Links:

  *   https://github.com/Azure/Azure-Network-Security/pull/37.patch<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37.patch&data=04%7C01%7CRoman.Anthony%40microsoft.com%7C3f865d2446154df4696208d8fb65d9a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762149883061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hZkC%2FMdGhSdNoDbCk5l7n1ipYLZkfm9lOc777x25HZs%3D&reserved=0>
  *   https://github.com/Azure/Azure-Network-Security/pull/37.diff<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37.diff&data=04%7C01%7CRoman.Anthony%40microsoft.com%7C3f865d2446154df4696208d8fb65d9a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762149893050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DBYaMnA3HX%2F13jm1uHLi81hfVsceZwAId3wbwpcq8hs%3D&reserved=0>

-

**Comment by anthony-roman** [comment]
Thank you for this feedback

I also found this line not to be working :
| where Action == "Drop"

I have had to change this line to
| where Action contains "Drop"
Confirmed the fallbackResourceIds in the JSON file as well.

\"fallbackResourceIds\":[\"/subscriptions/d1d8779d-38d7-4f06-91db-9cbc8de0176f/resourcegroups/soc/providers/microsoft.operationalinsights/workspaces/cybersecuritysoc\"],\"fromTemplateId\":\"sentinel-UserWorkbo

Following up with Chris on this for the PRs.

-Tobi

From: Anthony Roman ***@***.***>
Sent: Friday, April 9, 2021 7:45 AM
To: Azure/Azure-Network-Security ***@***.***>; Azure/Azure-Network-Security ***@***.***>; Chris Boehm ***@***.***>; Tobi Otolorin ***@***.***>
Cc: Review requested ***@***.***>
Subject: RE: [Azure/Azure-Network-Security] Firewall workbook application rule log changes (#37)

@Chris ***@***.***> will you and @Tobi ***@***.***> validate these changes please?

-Anthony

From: Reidar Johansen ***@***.******@***.***>>
Sent: Friday, April 9, 2021 10:44 AM
To: Azure/Azure-Network-Security ***@***.******@***.***>>
Cc: Anthony Roman ***@***.******@***.***>>; Review requested ***@***.******@***.***>>
Subject: [Azure/Azure-Network-Security] Firewall workbook application rule log changes (#37)


  *   Queries missing log entries where msg_s !has 'Web Category:' and msg_s has '. Url' and msg_s has '. No rule matched'
  *   rowLimit at default 250 is a bit small, increased to 10000 because I think that is more useful
  *   fallbackResourceIds is for a specific environment, better to use generic "Azure Monitor"

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Azure/Azure-Network-Security/pull/37<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37&data=04%7C01%7COluwatobi.Otolorin%40microsoft.com%7Cefa46b0bad984522960a08d8fb660992%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762953946201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CFx%2FRtKbk7lKFFaEN03r9E06BHscuXJ44Kkbf2uUaF8%3D&reserved=0>

Commit Summary

  *   Firewall workbook application rule log changes
  *   Firewall workbook application rule log changes

File Changes

  *   M Azure Firewall/Workbook - Azure Firewall Monitor Workbook/Azure Firewall_ARM.json<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37%2Ffiles%23diff-e54c61dfe845ded55e2ac0808377cf7d9de7bedf3be35ab7981c414bd3f9a116&data=04%7C01%7COluwatobi.Otolorin%40microsoft.com%7Cefa46b0bad984522960a08d8fb660992%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762953956196%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=85sPvUSvuBYubLUbXmX8CT2kf%2FODuX8FCGIAp1RHbTo%3D&reserved=0> (36)
  *   M Azure Firewall/Workbook - Azure Firewall Monitor Workbook/Azure Firewall_Gallery.json<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37%2Ffiles%23diff-bad4158317c6e17b3a5100d1747cdfb674e1c61234ac354d1e17f26a264226c9&data=04%7C01%7COluwatobi.Otolorin%40microsoft.com%7Cefa46b0bad984522960a08d8fb660992%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762953956196%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HchS7c9M0c4ni69U83E%2FQxYuGOZQIWPMb%2BRYR5pAH80%3D&reserved=0> (35)

Patch Links:

  *   https://github.com/Azure/Azure-Network-Security/pull/37.patch<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37.patch&data=04%7C01%7COluwatobi.Otolorin%40microsoft.com%7Cefa46b0bad984522960a08d8fb660992%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762953966191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FPzhQZEOWUcP7Wu2BoCtz8SfRArFB71B%2F3xAEdEafyw%3D&reserved=0>
  *   https://github.com/Azure/Azure-Network-Security/pull/37.diff<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Network-Security%2Fpull%2F37.diff&data=04%7C01%7COluwatobi.Otolorin%40microsoft.com%7Cefa46b0bad984522960a08d8fb660992%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535762953976187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lWGYlNq%2FHpcAarNt1XMBF%2BZUPil%2BDhoQIbOt86uzr1k%3D&reserved=0>

-

**Comment by reijoh** [comment]
> Thank you for this feedback I also found this line not to be working : | where Action == "Drop" I have had to change this line to | where Action contains "Drop" 

I cannot find the word Drop anywhere in the JSON files, but perhaps it is Deny?

Btw. we have to escape quotes and new line etc. in JSON. Why not write the queries with single quotes and no new lines? E.g. this:

```json
{
  "query": "where type =~ \"microsoft.operationalinsights/workspaces\"\r\n | project id, name | sort by name asc"
}
```

would be:

```json
{
  "query": "where type =~ 'microsoft.operationalinsights/workspaces' | project id, name | sort by name asc"
}
```

**Comment by chboeh** [comment]
@anthony-roman , @reijoh 
Thanks for the feedback:
The "fallbackResourceIds" was a mistake, needs to corrected.

Following up on a few things:

Queries missing log entries where msg_s !has 'Web Category:' and msg_s has '. Url' and msg_s has '. No rule matched'
**(Good feedback, odd how this was missed)**
rowLimit at default 250 is a bit small, increased to 10000 because I think that is more useful
**This was designed this way to speed up performance, but i'd agree more data shown is more useful.**
fallbackResourceIds is for a specific environment, better to use generic "Azure Monitor"
**Needs to be removed, thanks**
Fix query for SourceIPAddress (Investigation tab)
The '{SelectedSubscriptionId}' from the 'FQDN Traffic by Count' query is not the Subscription for the VM, it is the subscription for the firewall. Therefore the 'SourceIPAddress' query will not find any VM when filtering on this subscription id.
**Fantastic catch!**
Fix Azure Firewall Resource List query
The ProvisionedState column show FW is not running because it query for properties.ipConfigurations.[0].properties.provisioningState property, this property is not present for Microsoft.Network/azureFirewalls running as part of Virtual Hub.
**Odd i didn't run into this issue myself**


As for @anthony-roman, Where did you find this Action == "Drop"? I don't believe i use that reference anywhere. Wanting to track down this modification request.

**Comment by reijoh** [comment]
I am currently doing a bit more work on this workbook to improve it for my usage. I have started to analyze the queries used here and I think the way you do the queries is overcomplicated and allow for data rows being duplicated or missed. For example instead of this:

```kusto
let materializedData = materialize(AzureDiagnostics | where ResourceType == 'AZUREFIREWALLS' and OperationName == 'AzureFirewallApplicationRuleLog' and Category == 'AzureFirewallApplicationRule' | where ('{Resource:label}' !has ',' and Resource =~ '{Resource:label}') or ('{Resource:label}' has ',' and Resource in~ (split('{Resource:label}', ', '))) | project msg_s, Resource, TimeGenerated);union(materializedData | where msg_s has 'Web Category:' and msg_s has '. Url' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Url:' Url '. Action: ' Action '. Rule Collection:' RuleCollection '. Rule:' Rule '. Web Category:' WebCategory),(materializedData | where msg_s !has 'Web Category:' and msg_s has '. Url' and msg_s has '. No rule matched' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Url:' Url '. Action: ' Action '. No rule matched' *),(materializedData | where msg_s !has 'Web Category:' and msg_s !has '. Url' and msg_s has '. No rule matched' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Action: ' Action '. No rule matched' *),(materializedData | where msg_s has 'Web Category:' and msg_s !has '. Url' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Action: ' Action '. Rule Collection:' RuleCollection '. Rule:' Rule '. Web Category:' WebCategory),(materializedData | where msg_s !has 'Web Category:' and  msg_s !has '. Url' and msg_s !has 'Rule Collection' and msg_s !has ' Reason: ' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Action: ' Action '. ' RuleCollection '. ' Rule),(materializedData | where msg_s !has 'Web Category:' and  msg_s !has '. Url' and msg_s !has 'Rule Collection' and msg_s !has 'TLS extension was missing' | where msg_s has ' Reason:' | parse msg_s with Protocol ' request from ' Source ':' SourcePort '. Action: ' Action '. Reason: ' Rule '.'),(materializedData | where msg_s !has 'Web Category:' and  msg_s !has '. Url' and msg_s !has 'TLS extension was missing' and msg_s !has 'No rule matched' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Action: ' Action '. Rule Collection: ' RuleCollection '. Rule: ' Rule),(materializedData | where msg_s !has 'Web Category:' and  msg_s !has '. Url' and msg_s !has 'Rule Collection' and msg_s !has ' Reason: ' | where msg_s has 'Rule Collection Group' | parse msg_s with Protocol ' request from ' Source ':' SourcePort ' to ' Destination ':' DestinationPort '. Action: ' Action '. Policy:' Policy '. Rule Collection Group:' RuleCollectionGroup '. Rule Collection: ' RuleCollection '. Rule: ' Rule)
```

I would do:

```kusto
AzureDiagnostics | where ResourceType == 'AZUREFIREWALLS' and OperationName == 'AzureFirewallApplicationRuleLog' and Category == 'AzureFirewallApplicationRule' | where ('{Resource:label}' !has ',' and Resource =~ '{Resource:label}') or ('{Resource:label}' has ',' and Resource in~ (split('{Resource:label}', ', '))) | extend Protocol = extract(@'^([\S]+)', 1, msg_s), Source = extract(@'request from ([^ :]+)', 1, msg_s), SourcePort = extract(@'request from ([^ :]+):([0-9]+)', 2, msg_s), Destination = extract(@'request from ([^ :]+):([0-9]+) to ([^ :]+)', 3, msg_s), DestinationPort = extract(@'request from ([^ :]+):([0-9]+) to ([^ :]+):([0-9]+)', 4, msg_s), Url = trim_end(@'\.', extract(@'Url: ([\S]+)', 1, msg_s)), Action = extract(@'Action: ([\w]+)', 1, msg_s), Policy = trim_end(@'\.', extract(@'Policy: ([\S]+)', 1, msg_s)), RuleCollectionGroup = trim_end(@'\.', extract(@'Rule Collection Group: ([\S]+)', 1, msg_s)), RuleCollection = trim_end(@'\.', extract(@'Rule Collection: ([\S]+)', 1, msg_s)), Rule = trim_end(@'\.', extract(@'Rule: ([\S]+)', 1, msg_s)), WebCategory = trim_end(@'\.', extract(@'Web Category: ([\S]+)', 1, msg_s)), Reason = extract(@'Reason: ([^\.]+)(\.)', 1, msg_s), Firewall = Resource
```

I am using regex to extract data from msg_s instead of using parse. Remember that \ like in \S, must be escaped in the json file, e.g. \\S

When I am done I can share my workbook in my fork repo, but my final result may differ to much from your workbook so a pull request may not be of interest to you.

**Review by tobystic — CHANGES_REQUESTED** [review]
Hi @reijoh ,

Thank you very much for contributing to this repo. The feedback has been found very helpful. Before accepting and merging,  please consider changing the rowlimit value to 2000.  10,000 is 3900% increase. From performance perspective, we would like to make the default template values closer to average user attributes. Other users can increase values as they deem fit.

**Comment by reijoh** [comment]
> Thank you very much for contributing to this repo. The feedback has been found very helpful. Before accepting and merging, please consider changing the rowlimit value to 2000. 10,000 is 3900% increase. From performance perspective, we would like to make the default template values closer to average user attributes. Other users can increase values as they deem fit.

I have now updated everywhere 10000 rows was used and replaced with 2000

**Pull request merged**
