### PR TITLE
Updated ARM for new logging scheme

### PR DESCRIPTION
**Pull request by BigRollTide**
Updated the ARM template so that the new logging scheme can be used by the Workbook

### CODE REVIEW

**Comment by BigRollTide** [comment]
Updated the ARM template so that the new logging scheme can be used by the Workbook

@microsoft-github-policy-service agree

**Review by shabaz-github — COMMENTED** [review]
@BigRollTide Thank you for submitting the PR. Could you be a bit more specific about the changes you made please.

**Comment by shabaz-github** [comment]
@BigRollTide Could you please reply to the above comment.

**Comment by shabaz-github** [comment]
Closing this pull request as there is no response from the User - Please submit new pull request with the requested details.

**Pull request closed without merging**
